name: C/C++ CI

on:
    push:
        branches: [master]
        tags:
          - 'v*.*.*'
    pull_request:
        branches: [master]

jobs:
    build_ubuntu:
        name: Build on Ubuntu
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'recursive'
            - name: Build
              run: ./build.sh
            - name: Upload Distribution Files
              uses: actions/upload-artifact@v2
              with:
                name: Packages
                path: "*.deb"
            - name: Upload Packages to Release
              uses: svenstaro/upload-release-action@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: "*.deb"
                file_glob: true
                tag: ${{ github.ref }}
                overwrite: true
