name: C/C++ CI

on:
    push:
        branches: [master]
        tags:
          - 'v*.*.*'
    pull_request:
        branches: [master]

jobs:
    build_ubuntu:
        name: Build on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: 'recursive'
            - name: Build
              run: .\build.ps1
            - name: Upload Distribution Files
              uses: actions/upload-artifact@v2
              with:
                name: Packages
                path: build/*.zip
            - name: Upload Packages to Release
              uses: svenstaro/upload-release-action@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: build/*.zip
                file_glob: true
                tag: ${{ github.ref }}
                overwrite: true