name: C/C++ CI

on:
  push:
    branches: [master, remove-static-dependencies-and-build-scripts] # Add test branch to allow testing
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [master, remove-static-dependencies-and-build-scripts] # Allow PRs from test branch

jobs:
  build_windows:
    name: Build on Windows
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Cache the vcpkg installation to speed up subsequent builds
      - name: Cache vcpkg
        uses: actions/cache@v2
        with:
          path: ${{ env.VCPKG_ROOT }}
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      # Set up vcpkg if not cached
      - name: Set up vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg.git "$env:VCPKG_ROOT"
          cd "$env:VCPKG_ROOT"
          .\bootstrap-vcpkg.bat

      # Install dependencies using vcpkg
      - name: Install dependencies
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install --clean-after-build --triplet x64-windows

      # Configure CMake with vcpkg toolchain and set install prefix
      - name: Configure
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install

      # Build and install using CMake
      - name: Build and Install
        run: cmake --build build --config Release --target INSTALL

      # Package the installed files
      - name: Package files
        run: |
          Compress-Archive -Path .\build\install\* -DestinationPath .\build\nxs-windows-64bit.zip

      - name: Upload Distribution Files
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: build/nxs-windows-64bit.zip

      # - name: Upload Packages to Release
      #   uses: svenstaro/upload-release-action@v2
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: build/nxs-windows-64bit.zip
      #     file_glob: false
      #     tag: ${{ github.ref }}
      #     overwrite: true
